import Head from 'next/head'
import Textbox from "@/components/Textbox";
import SwapArrow from '@/components/SwapArrow';
import Style from '@/styles/Home.module.scss'
import { useEffect, useState } from 'react';
import {getLanguage, getTranslator} from './api/getLanguage';
import Modal from '@/components/Modal';
import TranslateButton from '@/components/TranslateButton';
import History from '@/components/History';

export default function Home() {

  const [showModal, setShowModal] = useState(null)
  const [inputLanguage, setInputLanguage] = useState("Thai")
  const [outputLanguage, setOutputLanguage] = useState("English")
  const [languages, setLanguages] = useState(null)
  const [textToTranslate, setTextToTranslate] = useState('')
  const [translatedText, setTranslatedText] = useState('')
  const [converterInputLang, setConverterInputLang] = useState('')
  const [converterOutputLang, setConverterOutputLang] = useState('')

  const [historyList, setHistoryList] = useState(null)

  useEffect(()=>{
    getLanguage(setLanguages)
  },[])

  useEffect(()=>{
    if(historyList==null){
      setHistoryList([])
    }else{
      setHistoryList([
        {
          inputLanguage: inputLanguage,
          outputLanguage: outputLanguage,
          inputText: textToTranslate,
          outputText: translatedText
        },
        ...historyList
      ])
    }
  },[translatedText])

  useEffect(()=>{
    convertToShort(setConverterInputLang, inputLanguage)
    convertToShort(setConverterOutputLang, outputLanguage)
  },[inputLanguage, outputLanguage])

  const handleSwapLanguage = () =>{
    setInputLanguage(outputLanguage)
    setOutputLanguage(inputLanguage)
  }

  const convertToShort = (setter, value) => {
    if(value == 'Thai'){
      setter('th')
    }if(value == 'Spainish'){
      setter('es')
    }if(value == 'English'){
      setter('en')
    }
  }

  return (
    <>
      <Head>
        <title>Traslator</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/faviconGT.ico" />
      </Head>

      <main>
        <div className={Style.container}>
          {showModal == null ?
          <>
            <Textbox
              type='input'
              selectedLanguage={inputLanguage}
              setShowModal={setShowModal}
              textToTranslate={textToTranslate}
              setTextToTranslate={setTextToTranslate}
              setTranslatedText={setTranslatedText}
            />

            <div className={Style.swapArrowContainer} onClick={handleSwapLanguage}>
              <SwapArrow/>
            </div>

            <Textbox
              type='output'
              selectedLanguage={outputLanguage}
              setShowModal={setShowModal}
              translatedText={translatedText}
            />

            <div 
              className='enterBtnContainer'
              onClick={()=>{
                getTranslator(converterOutputLang, converterInputLang, textToTranslate, setTranslatedText)
              }}
            >
                <TranslateButton/>
            </div>
          </> : ''}

          {showModal &&
            <Modal
              setShowModal={setShowModal}
              languages={languages}
              setChosenLanguage={showModal == 'input' ? setInputLanguage : setOutputLanguage}
              chosenLanguage={showModal == 'input' ? inputLanguage : outputLanguage}
            />
          }
        </div>

        <History historyList={historyList} setHistoryList={setHistoryList}/>

      </main>

    </>
  )
}
